rpmsg: qcom_glink_native: Fix compilation on k4.19
The [get|set]_sigs API is needed to preserve compatibility.
Switch back to it to fix the compilation errors after checking
out glink native module to k5.4.

This fixes the following compilation errors:

../drivers/rpmsg/qcom_glink_native.c:1247:14: error: too many arguments to function call, expected 3, have 4
                                    old, channel->rsigs);
                                         ^~~~~~~~~~~~~~
../drivers/rpmsg/qcom_glink_native.c:1780:3: error: field designator 'get_signals' does not refer to any field in type 'const struct rpmsg_endpoint_ops'; did you mean 'get_sigs'?
        .get_signals = qcom_glink_get_sigs,
         ^~~~~~~~~~~
         get_sigs
../drivers/rpmsg/rpmsg_internal.h:71:8: note: 'get_sigs' declared here
        int (*get_sigs)(struct rpmsg_endpoint *ept, u32 *lsigs, u32 *rsigs);
              ^
../drivers/rpmsg/qcom_glink_native.c:1780:17: error: incompatible function pointer types initializing 'int (*)(struct rpmsg_endpoint *, u32 *, u32 *)' (aka 'int (*)(struct rpmsg_endpoint *, unsigned int *, unsigned int *)') with an expression of type 'int (struct rpmsg_endpoint *)' [-Werror,-Wincompatible-function-pointer-types]
        .get_signals = qcom_glink_get_sigs,
                       ^~~~~~~~~~~~~~~~~~~
../drivers/rpmsg/qcom_glink_native.c:1781:3: error: field designator 'set_signals' does not refer to any field in type 'const struct rpmsg_endpoint_ops'; did you mean 'set_sigs'?
        .set_signals = qcom_glink_set_sigs,
         ^~~~~~~~~~~
         set_sigs
../drivers/rpmsg/rpmsg_internal.h:72:8: note: 'set_sigs' declared here
        int (*set_sigs)(struct rpmsg_endpoint *ept, u32 sigs);
              ^
../drivers/rpmsg/qcom_glink_native.c:1781:17: error: incompatible function pointer types initializing 'int (*)(struct rpmsg_endpoint *, u32)' (aka 'int (*)(struct rpmsg_endpoint *, unsigned int)') with an expression of type 'int (struct rpmsg_endpoint *, u32, u32)' (aka 'int (struct rpmsg_endpoint *, unsigned int, unsigned int)') [-Werror,-Wincompatible-function-pointer-types]
        .set_signals = qcom_glink_set_sigs,
                       ^~~~~~~~~~~~~~~~~~~

Fixes: 833692883 ("rpmsg: qcom_glink_native: Checkout to k5.4")
Signed-off-by: Tashfin Shakeer Rhythm <tashfinshakeerrhythm@gmail.com>
Signed-off-by: RyuujiX <saputradenny712@gmail.com>